apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  labels:
    zabbix-app: zabbix-server
    state: infra
    component: apiserver
    provider: kubernetes
  name: zabbix-loadbalancer
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
      zabbix-app: zabbix-server
      state: infra
  sessionAffinity: None
  type: LoadBalancer
